# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

palette = "catppuccin_macchiato"

# Prompt format
format = """
 $directory$git_branch$git_status$env_var $character"""


[env_var]
style = "pink"
variable = "CONDA_DEFAULT_ENV"
format = "[$env_value]($style)"

# Directory
[directory]
style = "blue"
truncation_length = 3
truncate_to_repo = false

# Git branch
[git_branch]
symbol = " "
style = "bold mauve"

# Git status
[git_status]
style = "red"

# Character prompt
[character]
success_symbol = "[](green)"
error_symbol = "[](red)"

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"
