wallpaper {
    monitor = eDP-1
    path = ~/Pictures/wallpapers/grey_arch_logo.png
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1 
    path = ~/Pictures/wallpapers/grey_arch_logo.png
    fit_mode = cover
}

